code --install-extension 4ops.terraform --force
code --install-extension alexcvzz.vscode-sqlite --force
code --install-extension analytic-signal.preview-pdf --force
code --install-extension BenRogersWPG.transparent-minimap --force
code --install-extension cschlosser.doxdocgen --force
code --install-extension formulahendry.code-runner --force
code --install-extension GrapeCity.gc-excelviewer --force
code --install-extension hashicorp.terraform --force
code --install-extension iocave.monkey-patch --force
code --install-extension jeff-hykin.better-cpp-syntax --force
code --install-extension lightbend.vscode-sbt-scala --force
code --install-extension mechatroner.rainbow-csv --force
code --install-extension ms-azuretools.vscode-azurefunctions --force
code --install-extension ms-azuretools.vscode-azureresourcegroups --force
code --install-extension ms-python.isort --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-toolsai.jupyter --force
code --install-extension ms-toolsai.jupyter-keymap --force
code --install-extension ms-toolsai.jupyter-renderers --force
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension ms-vscode-remote.remote-ssh --force
code --install-extension ms-vscode-remote.remote-wsl --force
code --install-extension ms-vscode.azure-account --force
code --install-extension ms-vscode.cmake-tools --force
code --install-extension ms-vscode.cpptools --force
code --install-extension ms-vscode.cpptools-extension-pack --force
code --install-extension ms-vscode.cpptools-themes --force
code --install-extension ms-vscode.remote-explorer --force
code --install-extension ms-vsliveshare.vsliveshare --force
code --install-extension ms-vsliveshare.vsliveshare-audio --force
code --install-extension ms-vsliveshare.vsliveshare-pack --force
code --install-extension mtxr.sqltools --force
code --install-extension mtxr.sqltools-driver-pg --force
code --install-extension paiqo.databricks-vscode --force
code --install-extension RandomFractalsInc.vscode-data-table --force
code --install-extension redhat.fabric8-analytics --force
code --install-extension redhat.java --force
code --install-extension redhat.vscode-commons --force
code --install-extension redhat.vscode-xml --force
code --install-extension scala-lang.scala --force
code --install-extension scalameta.metals --force
code --install-extension tonybaloney.vscode-pets --force
code --install-extension twxs.cmake --force
code --install-extension vadimcn.vscode-lldb --force
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples --force
code --install-extension VisualStudioExptTeam.vscodeintellicode --force
code --install-extension vscjava.vscode-java-debug --force
code --install-extension vscjava.vscode-java-dependency --force
code --install-extension vscjava.vscode-java-pack --force
code --install-extension vscjava.vscode-java-test --force
code --install-extension vscjava.vscode-maven --force
code --install-extension yzhang.markdown-all-in-one --force
